GET https://shopper-connection.herokuapp.com/product
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5ZDA0MmM1LWVhZTktNDQ3YS05MGE3LTE1ZmU3YTIyM2VhZiIsImlhdCI6MTY2NTU4MDgyNCwiZXhwIjoxNjY1NTk4ODI0fQ.Jn8LbRWYZvy0wTMT3bZXSvxHPY0zxMPlHgE-NjB0TN0


###
POST http://localhost:3003/user/signup
Content-Type: application/json 

{
    "userName": "agnaldo rocha test",
    "deliveryDate": "2023-10-11" 
}

###


POST https://shopper-connection.herokuapp.com/user/login
Content-Type: application/json 

{
    "userName": "Caila"
}

###

POST https://shopper-connection.herokuapp.com/purchase
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5ZDA0MmM1LWVhZTktNDQ3YS05MGE3LTE1ZmU3YTIyM2VhZiIsImlhdCI6MTY2NTQ5MjA3MCwiZXhwIjoxNjY1NTEwMDcwfQ.P0AP5-RS0BYbdVnuUIEFlQAg-H77dHjhGCQv0SiEQvc

{
"cartItems": [{ "id": 16, "name": "AZEITE  PORTUGUÊS EXTRA VIRGEM GALLO 500ML", "price": 20.49, "qty_stock": 156, "amout": 157 }, { "id": 18, "name": "BEBIDA ENERGÉTICA VIBE 2L", "price": 8.99, "qty_stock": 658, "amout": 659 }],
    "price": 100
}
