GET http://localhost:3003/product
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5ZDA0MmM1LWVhZTktNDQ3YS05MGE3LTE1ZmU3YTIyM2VhZiIsImlhdCI6MTY2NTE3NDYwMSwiZXhwIjoxNjY1MTc1MjAxfQ.iA3mqX9yzKww9QVDSOPJNc212jxKnKVuWNWmWbbS0zE
###

POST http://localhost:3003/user/signup
Content-Type: application/json 

{
    "userName": "benjamin duarte",
    "deliveryDate": "07/10/2022"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json 

{
    "userName": "benjamin duarte"
}

###

POST http://localhost:3003/purchase
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5ZDA0MmM1LWVhZTktNDQ3YS05MGE3LTE1ZmU3YTIyM2VhZiIsImlhdCI6MTY2NTE3OTE0OSwiZXhwIjoxNjY1MTk3MTQ5fQ.7RlpYQmsVHSU_auZF_nQ-cirNZ0W7PW9zrAQQK7A71A

{
"cartItems": [{ "id": "18", "name": "BEBIDA", "price": 20.49, "qty_stock": 158 }, { "id": 18, "name": "BEBIDA", "price": 20.49, "qty_stock": 158 }],
    "price": 100
}
